spring:
   application:
      name: customer-service
   cloud:
      stream:
         source: customerBinding-out-1
         kafka:
            binder:
            brokers: localhost:9092
            replicationFactor: 1
      bindings:
         customerBinding-out-0:
            destination: customer
            producer:
               partitionCount: 1
       